name: CI

on: push

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.16.2, 1.17.3]
        otp: ["25", "26", "27"]
        exclude:
          - elixir: 1.16.2
            otp: "27"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{matrix.otp}}-${{matrix.elixir}}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Format code
        run: mix format --check-formatted
      - name: Run tests
        run: mix test
